### ISSUE TITLE
Unexpected download error : Name or service not known

### ISSUE THREAD

**Issue by fhibler** [tpill90/battlenet-lancache-prefill#116] opened 2024-04-13 20:12 UTC
**Describe the bug**
Since April 13, 2024 I cannot prime any BattleNet content anymore. The container is starting, apps are being displayed, but when I start a download an error message occurs. The same setup works for Steam and Epic and has worked for BattleNet before.

Error message is:
Unexpected download error : Name or service not known  Skipping  app...

tcpdump reveals that the HTTP GET for /s2/cdns and /pro/cdns is successful though.

**Additional Details**
 - Linux (AlmaLinux 9.3) / Docker
 - Region : Germany

**Screenshots**
![Screenshot 2024-04-13 at 22 10 09](https://github.com/tpill90/battlenet-lancache-prefill/assets/1452221/f8dd667d-4e06-49e1-a03c-d9e4f32e6ba8)
![Screenshot 2024-04-13 at 22 10 15](https://github.com/tpill90/battlenet-lancache-prefill/assets/1452221/85ed97de-92f5-41e3-b7f3-3546dcb4186f)
![Screenshot 2024-04-13 at 22 11 30](https://github.com/tpill90/battlenet-lancache-prefill/assets/1452221/3f672e23-0c9c-4876-8191-b982d230b799)

**Comment by tpill90** [comment] 2024-05-07 18:45
Hi Florian,

Are you still seeing this issue a few weeks later?  If it is I can try to dig a bit deeper

**Comment by tpill90** [comment] 2024-05-26 19:28
Closing since I haven't received any further info.  Please feel free to reopen if the issue is still occurring.

**Closed by tpill90** 2024-05-26 19:28 UTC
